<?php
  $titles = array('fecha ingreso paciente', 
                  'Nombres paciente', 
                  'Apellidos paciente', 
                  'Sexo', 
                  'Fecha nacimiento', 
                  'Pais nacimiento', 
                  'Ciudad nacimiento', 
                  'Departamento nacimiento', 
                  'email digitador',
                  'Cedula paciente', 
                
                  'Fecha edicion paciente', 
                  'Celular pte', 
                  'Tel paciente', 
                  'EPS', 
                  'tipo vinculacion salud', 
                  'pais residencia', 
                  'ciudad residencia', 
                  'departamento residencia', 
                  'numero historia clinica', 

                  'redundante',
                  'fecha examen gases arteriales', 
                  'FIO2 gases arteriales', 
                  'pH gases arteriales', 
                  'paCO2 gases arteriales',
                  'paO2 gases arteriales', 
                  'HCO3 gases arteriales', 
                  'fecha examen pruebas coagulacion', 
                  'TPT', 
                  'TP', 
                  'INR',
                  'fecha examen stress test', 
                  'pico max VO2', 
                  'P.A. durante stress test', 
                  'pulso durante stress test', 
                  'medicamento', 
                  'otros medicamentos', 
                  'dosis', 
                  'fecha inicio medicamento', 
                  'fecha suspension medicamento',
                  'causa suspension medicamento', 
                  'evento adverso', 
                  'fecha examen doppler miembros inferiores', 
                  'doppler extremidad inf derecha', 
                  'otros datos doppler extremidades inferiores', 
                  'fecha examen ecocardio',
                  'via ecocardiografia', 
                  'PA durante ecocardio', 
                  'dilatacion cavidades derechas por ecocardio', 
                  'disfuncion cardiaca derecha por ecocardio', 
                  'derrame pleural por ecocardio', 
                  'disfuncion cardiaca izquierda por ecocardio', 
                  'fraccion eyeccion por ecocardio', 'TAPSE ecocardio',
                  'defectos congenitos cardiacos ecocardio', 
                  'otros defectos congenitos ecocardio', 
                  'desviacion septum ecocardio', 
                  'fecha examen electroCG', 
                  'eje electroCG', 
                  'patron electroCG',
                  'frecuencia electroCG', 
                  'Tipo ritmo electroCG', 
                  'medico tratante', 
                  'raza afroamericanan',
                  'fecha de diagnostico de primera vez', 
                  'anos sintomatico', 
                  'fecha examen medico', 
                  'oxigeno domiciliario',
                  'nro horas oxigeno domiciliario', 
                  'disnea', 
                  'tos', 
                  'dolor toracico', 
                  'edema extremidades inferiores',
                  'hemoptisis', 
                  'sincope', 
                  'mejoria de sintomas', 
                  'embarazo', 
                  'peso evaluacion de seguimiento', 
                  'talla evaluacion de seguimiento', 
                  'clase funcional NYHA', 
                  'saturacion oxigeno evaluacion de seguimiento',
                  'pulso evaluacion de seguimiento', 
                  'presion arterial evaluacion de seguimiento',
                  'frecuencia respiratoria evaluacion de seguimiento', 
                  'soplo tricuspideo evaluacion de seguimiento',
                  'p2 mayor que a2 evaluacion de seguimiento', 
                  'cianosis evaluacion de seguimiento', 
                  'hepatomegalia evaluacion de seguimiento', 
                  'edema evaluacion de seguimiento',
                  'ing yugular evaluacion de seguimiento', 
                  'dedos palillo de tambor evaluacion de seguimiento',
                  'fecha examen gamagrafia VP', 
                  'TEP por gamagrafia pulm', 
                  'defectos encontrados en gamagrafia pulm',
                  'fecha examen hemoglobina', 
                  'hemoglobina mg/dl', 
                  'fecha examen pruebas tiroideas', 
                  'TSH', 
                  't4 total',
                  't4 libre', 
                  'fecha examen pruebas hepaticas', 
                  'albumina', 
                  'AST', 
                  'ALT', 
                  'FAL liver', 
                  'GGT', 
                  'bilirrubina T',
                  'bilirrubina dir', 
                  'fecha examen funcion renal', 
                  'creatinina', 
                  'BUN', 
                  'fecha examen caminata 6 mins',
                  'metros caminados', 
                  'FI02 prueba caminata', 
                  'SatO2 inicial caminata', 
                  'SatO2 final caminata', 
                  'sintomas durante caminata', 
                  'BORG caminata', 
                  'sincope durante caminata', 
                  'dolor toracico durante caminata',
                  'digitador', 
                  'hospital', 
                  'timestamp registro de datos');

    function info_patients(){
      
    }
?>